-- Create Database
CREATE DATABASE IF NOT EXISTS college_agency_db;
USE college_agency_db;

-- Table: colleges
CREATE TABLE IF NOT EXISTS colleges (
  college_id INT AUTO_INCREMENT PRIMARY KEY,
  college_name VARCHAR(200),
  degree VARCHAR(100),
  district VARCHAR(100),
  fees INT,
  description TEXT
);

-- Table: enquiries
CREATE TABLE IF NOT EXISTS enquiries (
  enquiry_id INT AUTO_INCREMENT PRIMARY KEY,
  student_name VARCHAR(150),
  phone VARCHAR(15),
  email VARCHAR(150),
  interested_degree VARCHAR(100),
  college_id INT,
  enquiry_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (college_id) REFERENCES colleges(college_id) ON DELETE SET NULL
);

-- Table: admin
CREATE TABLE IF NOT EXISTS admin (
  admin_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE,
  password VARCHAR(255)
);

-- Insert Dummy Data for Colleges
INSERT INTO colleges (college_name, degree, district, fees, description) VALUES
('Tech Institute of Chennai', 'B.E', 'Chennai', 85000, 'A premier institute for engineering.'),
('Arts & Science College', 'B.Sc', 'Madurai', 30000, 'Quality education in arts and sciences.'),
('Global Management School', 'MBA', 'Coimbatore', 120000, 'Top-tier management studies.'),
('City Computing College', 'BCA', 'Trichy', 40000, 'Focused on computer applications.'),
('National Engineering College', 'B.E', 'Chennai', 90000, 'Excellent infrastructure and placement.'),
('Green Valley Arts', 'B.A', 'Salem', 25000, 'Promoting liberal arts education.'),
('Future Tech Academy', 'MCA', 'Bangalore', 60000, 'Advanced masters program in computer application.');

-- Insert Dummy Admin (Password: admin123)
-- Note: In a real scenario, use the hashed password generated by the backend.
-- For this setup, you might need to manually update this after generating a hash, 
-- or use the registration flow if we build one (though req only asks for login).
-- Let's assume a pre-hashed password for 'admin123' using bcrypt default rounds (10).
-- Hash for 'admin123': $2b$10$YourHashedPasswordHere (Placeholder, purely illustrative for SQL file)
-- Actual implementation will rely on the backend to verify/create.
